# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f53932058f1aff471bbf443340a62a8149a6438baa48dd551aa96893f096bdcdb704509ec48926211f831f6a2bd4d1a5983610068e53de80214ad585e53341

test:
  secret_key_base: 11d952881dd0869b66f13f53d9e6660cb48fafb0bc34db04be3ce822b51bb25a1e6fde5c0e231e29c156e18ba9de5a79d7571b4b91ea61488828e2765a997f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
